
services:
  fitbit_api:
    build: 
      context: ./src/api
      dockerfile: Dockerfile
    container_name: task2_api
    environment:
      - DB_HOST=task1_timescaledb
      - DB_PORT=5432
      - DB_NAME=fitbit_data
      - DB_USER=fitbit_user
      - DB_PASSWORD=fitbit_password
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - task1_fitbit_network

networks:
  task1_fitbit_network:
    external: true
#     depends_on:
#       - timescaledb
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
#       interval: 30s
#       timeout: 10s
#       retries: 3

#   fitbit_dashboard:
#     build: 
#       context: ./src/frontend
#       dockerfile: Dockerfile
#     container_name: task2_frontend
#     environment:
#       - REACT_APP_API_URL=http://localhost:8000
#     ports:
#       - "3000:3000"
#     networks:
#       - fitbit_network
#     restart: unless-stopped
#     depends_on:
#       - fitbit_api

#   # Use TimescaleDB from Task 1
#   timescaledb:
#     image: timescale/timescaledb:2.11.0-pg15
#     container_name: task1_timescaledb
#     environment:
#       POSTGRES_DB: fitbit_data
#       POSTGRES_USER: fitbit_user
#       POSTGRES_PASSWORD: fitbit_password
#       POSTGRES_HOST_AUTH_METHOD: trust
#     ports:
#       - "5432:5432"
#     volumes:
#       - timescale_data:/var/lib/postgresql/data
#     networks:
#       - fitbit_network
#     restart: unless-stopped

# volumes:
#   timescale_data:
#     external: true

# networks:
#   fitbit_network:
#     driver: bridge
