
services:
  fitbit_api:
    build: 
      context: ./src/api
      dockerfile: Dockerfile
    container_name: task2_api
    environment:
      - DB_HOST=task1_timescaledb
      - DB_PORT=5432
      - DB_NAME=fitbit_data
      - DB_USER=fitbit_user
      - DB_PASSWORD=fitbit_password
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - task1_fitbit_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  task1_fitbit_network:
    external: true
